# Makefile for source code

# Parameters to control Makefile Execution

CC = gcc
VARNAME = value
CFLAGS = -ansi -pedantic -Wall -g

# Entries to bring Makefile up-to-date

## final_object_name: module1.o module2.o
# 	$ (CC) $ (CFLAGS) -o final_object_name module1.o module2.o

# module1.o: module1.h file.c
# 	$ (CC) $ (CFLAGS) -o file.c
# module2.o: module2.h main.c
# 	$ (CC) $ (CFLAGS) -o main.c
